name: Deploy

on:
    workflow_dispatch:

jobs:
    deploy:
        name: Build and Deploy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Deploy via SCP
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.MAIN_SERVER_IP }}
                  username: ${{ secrets.MAIN_SERVER_USER }}
                  key: ${{ secrets.ED_KEY }}
                  port: ${{ secrets.MAIN_SERVER_PORT }}
                  source: "test"
                  target: "/var/www"
